package com.redhat.demos.cwtbookingdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleOut implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Executive Rule Output")
   private java.lang.String execRule;

   @org.kie.api.definition.type.Label("Payment Rule Result")
   private java.lang.String paymentrule;

   @org.kie.api.definition.type.Label(value = "Date Rules Output")
   private java.lang.String dateRule;

   public RuleOut()
   {
   }

   public java.lang.String getExecRule()
   {
      return this.execRule;
   }

   public void setExecRule(java.lang.String execRule)
   {
      this.execRule = execRule;
   }

   public java.lang.String getPaymentrule()
   {
      return this.paymentrule;
   }

   public void setPaymentrule(java.lang.String paymentrule)
   {
      this.paymentrule = paymentrule;
   }

   public java.lang.String getDateRule()
   {
      return this.dateRule;
   }

   public void setDateRule(java.lang.String dateRule)
   {
      this.dateRule = dateRule;
   }

   public RuleOut(java.lang.String execRule, java.lang.String paymentrule,
         java.lang.String dateRule)
   {
      this.execRule = execRule;
      this.paymentrule = paymentrule;
      this.dateRule = dateRule;
   }

public String toString(){
    return "ResultofAllRules:"+"..Exec Rule:"+execRule +"..Payment Rule:"+paymentrule+"..Date Rule:"+dateRule;
}
}