package com.redhat.demos.cwtbookingdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TravelerProfile implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Traveler Profile ID")
   private java.lang.String travelerID;
   @org.kie.api.definition.type.Label("Corporate Profile")
   private com.redhat.demos.cwtbookingdemo.CorporateProfile corpProfile;

   @org.kie.api.definition.type.Label("First Name")
   private java.lang.String firstName;

   @org.kie.api.definition.type.Label("Family/Last Name")
   private java.lang.String surName;

   @org.kie.api.definition.type.Label("Country of Residence")
   private java.lang.String residenceCountryCode;

   @org.kie.api.definition.type.Label("Effective Date")
   private java.util.Date profileEffectiveDate;

   @org.kie.api.definition.type.Label("Profile Active Indicator")
   private java.lang.Boolean profileActive;

   @org.kie.api.definition.type.Label("Executive Level")
   private java.lang.String executiveLevel;

   @org.kie.api.definition.type.Label(value = "Frequent Flyer Number")
   private java.lang.String FFID;

   public TravelerProfile()
   {
   }

   public java.lang.String getTravelerID()
   {
      return this.travelerID;
   }

   public void setTravelerID(java.lang.String travelerID)
   {
      this.travelerID = travelerID;
   }

   public com.redhat.demos.cwtbookingdemo.CorporateProfile getCorpProfile()
   {
      return this.corpProfile;
   }

   public void setCorpProfile(
         com.redhat.demos.cwtbookingdemo.CorporateProfile corpProfile)
   {
      this.corpProfile = corpProfile;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getSurName()
   {
      return this.surName;
   }

   public void setSurName(java.lang.String surName)
   {
      this.surName = surName;
   }

   public java.lang.String getResidenceCountryCode()
   {
      return this.residenceCountryCode;
   }

   public void setResidenceCountryCode(java.lang.String residenceCountryCode)
   {
      this.residenceCountryCode = residenceCountryCode;
   }

   public java.util.Date getProfileEffectiveDate()
   {
      return this.profileEffectiveDate;
   }

   public void setProfileEffectiveDate(java.util.Date profileEffectiveDate)
   {
      this.profileEffectiveDate = profileEffectiveDate;
   }

   public java.lang.Boolean getProfileActive()
   {
      return this.profileActive;
   }

   public void setProfileActive(java.lang.Boolean profileActive)
   {
      this.profileActive = profileActive;
   }

   public java.lang.String getExecutiveLevel()
   {
      return this.executiveLevel;
   }

   public void setExecutiveLevel(java.lang.String executiveLevel)
   {
      this.executiveLevel = executiveLevel;
   }

   public java.lang.String getFFID()
   {
      return this.FFID;
   }

   public void setFFID(java.lang.String FFID)
   {
      this.FFID = FFID;
   }

   public TravelerProfile(java.lang.String travelerID,
         com.redhat.demos.cwtbookingdemo.CorporateProfile corpProfile,
         java.lang.String firstName, java.lang.String surName,
         java.lang.String residenceCountryCode,
         java.util.Date profileEffectiveDate, java.lang.Boolean profileActive,
         java.lang.String executiveLevel, java.lang.String FFID)
   {
      this.travelerID = travelerID;
      this.corpProfile = corpProfile;
      this.firstName = firstName;
      this.surName = surName;
      this.residenceCountryCode = residenceCountryCode;
      this.profileEffectiveDate = profileEffectiveDate;
      this.profileActive = profileActive;
      this.executiveLevel = executiveLevel;
      this.FFID = FFID;
   }

}